// params.scad - GENERATED by case_pair.py from boards.json and the DIMS table. Do not edit:
// change case_pair.py (or pass -D NAME=value to openscad for a quick what-if) and regenerate.
// World frame: X across the front from the clock's left, Y up (FreeCAD assembly), Z depth
// from the ИН-12 glass front, + toward the back. case.scad maps x = X, y = Z, z = Y.
// Kinds: board = read from the board files; doc = stated in a repo document; design = chosen
// here; assumed = typical value, not yet measured.


// ---- boards
BOARD_W            = 191.4;  // [board] tools/mkpcb_disp.py W = tools/mkpcb_drv.py W
DISP_H             = 44;  // [board] tools/mkpcb_disp.py H
DISP_TOP_Y         = 78;  // [board] tools/mkpcb_disp.py TOP: world Y of TS06-DISP's top edge
DRV_H              = 100;  // [board] tools/mkpcb_drv.py H
DRV_Y0             = 26;  // [board] tools/mkpcb_drv.py Y0: TS06-DRV's top edge is 26 above TS06-DISP's
PCB_T              = 1.6;  // [board] tools/pcbkit.py Board.thickness (both boards)
FASCIA_W           = 176;  // [board] PCB/TS06-FASCIA/TS06-FASCIA.kicad_pcb Edge.Cuts
FASCIA_H           = 40;  // [board] PCB/TS06-FASCIA/TS06-FASCIA.kicad_pcb Edge.Cuts (was 52, PCB/README.md)
FASCIA_X0          = 4.305;  // [design] the owner, 29.09.26: the fascia centred under the tube row, on the middle of H10 and ИН-15А (X 92.305), kept within the board width
FASCIA_T           = 2;  // [doc] PCB/README.md: TS06-FASCIA 2.0 mm FR4
FASCIA_HOLE_D      = 2.7;  // [board] TS06-FASCIA.kicad_pcb mounting holes (M2.5)

// ---- stack
PBS_H              = 8.5;  // [doc] PCB/TS06-DRV/bom.md: socket strip PBS, 8.5 mm (review finding 1: PBS runs 7.0-8.5)
PLS_BODY           = 2.5;  // [doc] PCB/TS06-DISP/bom.md: 11 mm = 8.5 PBS + 2.5 PLS body
IN12_W             = 19.47;  // [doc] 3d/IN12.FCStd envW (render/rev_f.py DIMS)
IN12_H             = 28.86;  // [doc] 3d/IN12.FCStd envH (render/rev_f.py DIMS)
IN12_D             = 25.5;  // [doc] 3d/IN12.FCStd envD: glass front to rear seating plane (measurements-IN12)
IN12_DIGIT         = 18.63;  // [doc] render/rev_f.py DIGIT_12, caliper 27.08
IN12_SEAT          = 4.5;  // [assumed] socket seat: review puts the socketed glass front ~30 in front of TS06-DISP; TS06-LIB-SOCKET is not captured
IN17_FACE          = 14;  // [doc] ИН-17 outline drawing: face 14 (measurements-IN17 Rev 5)
IN17_H             = 20;  // [doc] ИН-17 outline drawing: 20 across the long face axis
IN17_D             = 22;  // [doc] ИН-17 outline drawing: glass 22 long
IN17_STEM          = 20;  // [doc] ИН-17 outline drawing: round stem Ø20 at the base
IN17_DIGIT         = 9;  // [doc] render/rev_f.py DIGIT_17
IN17_STANDOFF_MIN  = 6.4;  // [doc] TS06_IN17_Socket descr: >= 6.4 mm glass to board (TU: no solder within 8 mm)
GLASS_ALLOW        = 0.4;  // [doc] TERMINAL-06-cad-component-library.md §7: glass gets max-of-sample + 0.4
LED_D              = 3;  // [board] TS06_LED_D3.0mm
LED_H              = 5.3;  // [assumed] 3 mm LED body height above the board
LED_FLANGE_D       = 3.8;  // [assumed] 3 mm LED flange diameter
INS1_D             = 6.97;  // [doc] TS06_INS1_Lamp descr: measured 6.97 mm envelope
PIN_TAIL           = 1.5;  // [assumed] trimmed through-hole lead + fillet proud of a board face
SCREW_HEAD         = 2;  // [assumed] M3 low head (DIN 7984 2.0; ISO 7380 1.65) - review finding 3
SCREW_HEAD_D       = 5.5;  // [assumed] M3 low-head diameter

// ---- design
CHEEK_T            = 6;  // [doc] pair review, envelope: 6 mm cheeks
CHEEK_CLR          = 0.5;  // [doc] pair review, envelope: 0.5 mm each side
GLASS_RECESS       = 1;  // [design] tube glass sits 1 mm behind the face plane, so a knock lands on the case
SILL_TOP_Y         = 39;  // [design] trench floor: above the XP21-25 pads (37.55; review: >= 38), below the ИН-17 LEDs' flange (41.49 - 1.9 = 39.59)
SILL_T             = 2;  // [design] printed
BACK_GAP           = 2.5;  // [design] no case part closer than this to TS06-DISP's front face (pin tails, screw heads)
TRENCH_L_X         = 3;  // [doc] pair review 4: the trench's left wall hides XP11, the left 3 mm
TRENCH_R_X         = 182.035;  // [design] right wall: ИН-15А (V10) glass + GLASS_ALLOW + 0.5, still hiding the H4 standoff screw and XP12's end
BROW_CLR           = 0.8;  // [design] soffit above the tall glass: 2 x GLASS_ALLOW
VALANCE_Y0         = 74;  // [doc] pair review 3: the brow covers the display board's top 4 mm (78 - 4)
VALANCE_T          = 1.5;  // [design] printed rib behind the ИН-17 pair
BROW_T             = 3;  // [design] printed brow face
SOFFIT_T           = 2;  // [design] printed
BROW_RAKE          = 12;  // [doc] spec §6: front raked 12° - the brow leans back like the fascia
TOP_CLR            = 3;  // [doc] pair review, envelope: 3 mm of top clearance
TOP_T              = 3;  // [design] printed top bar
REAR_AIR           = 5;  // [doc] pair review, envelope: 5 mm of air in front of the rear panel
REAR_T             = 1.6;  // [doc] pair review suggestion 2: the rear panel is a 1.6 mm FR4 blank
BASE_T             = 3;  // [design] printed or 3 mm aluminium
KICK_T             = 2;  // [design] the raked strip under the fascia; thin enough to clear the fascia plug
FASCIA_RAKE        = 12;  // [doc] spec §6 and cad-component-library: front raked 12°
FLOOR_CLR          = 0.5;  // [design] between the fascia lead's lowest point and the floor
VENT_W             = 2;  // [doc] pair review 4: slots no wider than 2.5 mm (2.0 used)
VENT_X0            = 100;  // [doc] pair review suggestion 2: vents above the converter, world X 100-130
VENT_X1            = 130;  // [doc] pair review suggestion 2
VENT_Y0            = 85;  // [doc] pair review suggestion 2: world Y 85-100
VENT_Y1            = 100;  // [doc] pair review suggestion 2
VENT_PITCH         = 4.5;  // [design] 
BOSS_W             = 8;  // [design] square boss on a cheek's inner face, M3 heat-set insert
BOSS_D             = 10;  // [design] boss length in Z, in front of TS06-DRV
FBOSS_D            = 8;  // [design] fascia boss depth behind the fascia
JACK_HOLE_D        = 9;  // [doc] pair review suggestion 3: Ø9 through
JACK_CB_D          = 14;  // [doc] pair review suggestion 3: Ø14 pocket (put on the OUTSIDE here - see checks)
JACK_WEB           = 1.5;  // [doc] pair review suggestion 3: thin the cheek to 1.5-2 mm
USB_SLOT_W         = 12;  // [doc] pair review suggestion 3: slot about 12 x 9 (12 along Y)
USB_SLOT_H         = 9;  // [doc] pair review suggestion 3 (9 along Z)
VIEW_DEG           = 10;  // [doc] cad-component-library §5 / spec §6: brow clearance at a 10° viewing angle

// ---- parts
JACK_BODY_L        = 14.5;  // [board] TS06_BarrelJack_Horizontal F.Fab: x -13.70..0.80
JACK_BODY_W        = 9;  // [board] TS06_BarrelJack_Horizontal F.Fab: y -4.51..4.50
JACK_BODY_H        = 11;  // [assumed] 5.5 x 2.1 PCB jack body height (PJ-002A class)
JACK_AXIS_H        = 6.5;  // [assumed] barrel axis above the board (PJ-002A class)
PLUG_BARREL_L      = 9.5;  // [assumed] 5.5 x 2.1 plug sleeve length (common 9.5; long-barrel 12/14 exist)
PLUG_NOSE_D        = 10;  // [assumed] plug overmould nose - larger than the Ø9 hole, so it stops on the web
JACK_ENGAGE_MIN    = 7;  // [assumed] sleeve engagement for both contacts to make
NANO_PCB_T         = 1.6;  // [assumed] Arduino Nano board
USB_H              = 4;  // [assumed] mini-B receptacle height above the Nano board
USB_W              = 7.7;  // [assumed] mini-B receptacle width
USB_L              = 9.2;  // [assumed] mini-B receptacle length
USB_PLUG_W         = 11;  // [assumed] mini-B plug overmould across Y
USB_PLUG_H         = 8;  // [assumed] mini-B plug overmould across Z
FJ_HDR_H           = 4.8;  // [assumed] JST S6B-PH-SM4-TB housing height off the fascia's back
FJ_PLUG_OUT        = 3;  // [assumed] mated PHR-6 beyond the header mouth, to where the wires leave it
CABLE_R            = 3;  // [assumed] bend radius of the 6-wire PH lead (to the ribbon's centre line)
CABLE_HALF         = 0.65;  // [assumed] half the lead's thickness (6 x AWG28 side by side)
J1_MATED_H         = 9.5;  // [assumed] B6B-PH-K 6.0 header + PHR-6 housing, off TS06-DRV's display-facing face
LEAD_LEN           = 150;  // [doc] pair review suggestion 5: a 150 mm PHR-6 lead
ROTARY_D           = 26.94;  // [doc] TERMINAL-06-concept-plates: rotary body 26.94 (caliper 28.08)
ROTARY_DEPTH       = 16;  // [assumed] rotary body + lugs behind the fascia (spec §6: lugs >= 11.3 behind it)
MT1_W              = 11.92;  // [doc] measurements-MT1 #2 (candidate W)
MT1_L              = 10.43;  // [doc] measurements-MT1 #1 (candidate L)
MT1_DEPTH          = 30;  // [assumed] cad-component-library: 'your spec says 30 mm depth; verify per sample'
KMD1_A             = 13.75;  // [doc] measurements-KMD1 #1 (orientation not known)
KMD1_B             = 16.91;  // [doc] measurements-KMD1 #2 (orientation not known)
KMD1_DEPTH         = 20;  // [assumed] КМД1-1 body depth: not captured (measurements-KMD1 #8)

// ---- read from the boards (world coordinates)
IN12_X   = [13.21, 36.57, 63.99, 87.37];  // board: mkpcb_disp IN12_X (H10 H1 M10 M1)
IN15_X   = [150.4, 171.4];  // board: mkpcb_disp IN15_X (ИН-15Б, ИН-15А)
IN17_X   = [108.635, 129.135];  // board: mkpcb_disp IN17_X (S10, S1)
IN12_Y   = 60.166;  // board: TOP - Y12
IN17_Y   = 54.791;  // board: TOP - Y17
COLON    = [[50.535, 66.5], [50.535, 52.5]];  // board: V7, V8 (ИНС-1)
LEDS     = [[13.21, 42.496], [36.57, 42.496], [63.99, 42.496], [87.37, 42.496], [108.635, 41.491], [129.135, 41.491], [150.4, 42.496], [160.9, 42.496], [171.4, 42.496]];  // board: HL1-HL9
DISP_HOLES = [[3.5, 37.5], [187.9, 37.5], [50.535, 74.7], [187.9, 70.5]];  // board: mkpcb_disp H1-H4 (M3, the standoffs)
DRV_CASE_HOLES = [[187.9, 7.5], [3.5, 7.5], [187.9, 100.5], [3.5, 81.5]];  // board: mkpcb_drv HOLES H5-H8 -> cheeks
DISP_STRIPS = [["XP11", -0.17, 3.37, 48.97, 75.37], ["XP12", 105.58, 185.32, 74.03, 77.57], ["XP21", 10.17, 23.87, 34.93, 38.47], ["XP22", 46.22, 54.84, 34.93, 38.47], ["XP23", 67.51, 78.67, 34.93, 38.47], ["XP24", 113.345, 124.505, 34.93, 38.47], ["XP25", 152.78, 169.02, 34.93, 38.47]];  // board: XP courtyards [ref, X0, X1, Y0, Y1]
// TS06-DRV parts [ref, X0, X1, Y0, Y1, height, side]: side 0 = component face (to the rear),
// 1 = display face. Boxes are courtyards; heights per case_pair.py FP_H (kind in checks.md).
DRV_PARTS = [
  ["C1", 166.68, 173.78, 20.975, 23.975, 10, 0],
  ["C10", 153.62, 156.62, 84.335, 91.435, 10, 0],
  ["C11", 158.065, 161.065, 83.065, 90.165, 10, 0],
  ["C12", 101.215, 108.315, 82.72, 85.72, 10, 0],
  ["C13", 82.455, 85.455, 86.24, 93.34, 10, 0],
  ["C14", 88.85, 95.95, 96.8, 99.8, 10, 0],
  ["C15", 145.82, 152.92, 52.965, 55.965, 10, 0],
  ["C16", 153.44, 160.54, 52.965, 55.965, 10, 0],
  ["C17", 109.79, 116.89, 52.665, 55.665, 10, 0],
  ["C3", 76.45, 83.55, 82.72, 85.72, 10, 0],
  ["C4", 19, 22, 49.45, 56.55, 10, 0],
  ["C5", 37.55, 42.15, 52.45, 54.55, 8, 0],
  ["C6", 37.55, 42.15, 54.95, 57.05, 8, 0],
  ["C7", 111.15, 121.65, 92.75, 103.25, 20, 0],
  ["C8", 146.25, 153.05, 96.8, 103.6, 12.5, 0],
  ["C9", 149.81, 152.81, 89.415, 96.515, 10, 0],
  ["F1", 155.85, 173.85, 98.95, 102.45, 13, 0],
  ["J1", 41.55, 56.45, 6.8, 12.3, 9.5, 1],
  ["L1", 135.15, 147.65, 84.25, 96.75, 16, 0],
  ["R1", 52, 55, 58.51, 63.6, 11, 0],
  ["R20", 6.285, 9.285, 43.475, 48.565, 11, 0],
  ["R21", 25.7, 28.7, 57.49, 69.75, 3.5, 0],
  ["R22", 31.4, 34.4, 57.49, 69.75, 3.5, 0],
  ["R23", 33.9, 36.9, 76.41, 81.5, 11, 0],
  ["R24", 36.9, 39.9, 76.41, 81.5, 11, 0],
  ["R25", 39.9, 42.9, 76.41, 81.5, 11, 0],
  ["R26", 59, 62, 58.51, 63.6, 11, 0],
  ["R27", 15.97, 30.77, 42.35, 46.05, 4.5, 0],
  ["R28", 18.51, 33.31, 38.55, 42.25, 4.5, 0],
  ["R29", 58.07, 72.87, 38.55, 42.25, 4.5, 0],
  ["R30", 60.61, 75.41, 42.35, 46.05, 4.5, 0],
  ["R31", 116.605, 131.405, 42.35, 46.05, 4.5, 0],
  ["R32", 119.145, 133.945, 38.55, 42.25, 4.5, 0],
  ["R33", 15.735, 20.825, 28.46, 31.46, 11, 0],
  ["R34", 15.735, 20.825, 24.65, 27.65, 11, 0],
  ["R35", 10.02, 15.11, 28.46, 31.46, 11, 0],
  ["R36", 10.02, 15.11, 24.65, 27.65, 11, 0],
  ["R37", 73.365, 78.455, 38.55, 41.55, 11, 0],
  ["R38", 79.08, 84.17, 39.185, 42.185, 11, 0],
  ["R39", 75.905, 80.995, 42.995, 45.995, 11, 0],
  ["R40", 81.805, 84.805, 42.81, 47.9, 11, 0],
  ["R41", 110.83, 115.92, 41.725, 44.725, 11, 0],
  ["R42", 105.115, 110.205, 41.725, 44.725, 11, 0],
  ["R43", 118.635, 121.635, 46.62, 51.71, 11, 0],
  ["R44", 112.735, 117.825, 49.345, 52.345, 11, 0],
  ["R53", 55.5, 58.5, 58.51, 63.6, 11, 0],
  ["R54", 37.55, 42.64, 46.4, 49.4, 11, 0],
  ["R55", 37.55, 42.64, 49.4, 52.4, 11, 0],
  ["R56", 156.04, 170.84, 39.15, 42.85, 4.5, 0],
  ["R57", 163.66, 178.46, 42.95, 46.65, 4.5, 0],
  ["R58", 43.65, 47.35, 39.65, 54.45, 4.5, 0],
  ["R59", 47.65, 51.35, 39.65, 54.45, 4.5, 0],
  ["R60", 101.345, 116.145, 45.3, 49, 4.5, 0],
  ["R61", 86.105, 100.905, 45.3, 49, 4.5, 0],
  ["R62", 81.65, 96.45, 99.85, 103.55, 4.5, 0],
  ["R63", 77.95, 81.65, 87.95, 102.75, 4.5, 0],
  ["R64", 65.69, 77.95, 90.5, 93.5, 3.5, 0],
  ["R65", 65.69, 77.95, 98.5, 101.5, 3.5, 0],
  ["R66", 48.5, 51.5, 58.51, 63.6, 11, 0],
  ["R67", 121.35, 133.61, 88.9, 91.9, 3.5, 0],
  ["R68", 122.09, 134.35, 96.055, 99.055, 3.5, 0],
  ["R69", 105.1, 108.1, 87.95, 100.21, 3.5, 0],
  ["R70", 101.6, 104.6, 87.95, 100.21, 3.5, 0],
  ["R71", 98.1, 101.1, 87.95, 100.21, 3.5, 0],
  ["RN1", 145.32, 166.26, 20.48, 31.14, 8.5, 0],
  ["RP1", 64.42, 74.46, 83.33, 88.66, 10.5, 0],
  ["U1", -2.4, 43.82, 85.2, 103.48, 16.6, 0],
  ["U10", 131.975, 137.675, 46.18, 56.84, 8.5, 0],
  ["U11", 108.88, 119.54, 81.72, 92.5, 8.5, 0],
  ["U12", 85.88, 96.54, 84.42, 95.2, 8.5, 0],
  ["U13", 58.4, 72.1, 27.96, 31.5, 22, 0],
  ["U14", 161.36, 173.47, 82.25, 91.25, 10.5, 0],
  ["U15", 136.79, 157.73, 60.86, 71.52, 8.5, 0],
  ["U16", 159.11, 180.05, 60.86, 71.52, 8.5, 0],
  ["U17", 105.77, 126.71, 60.86, 71.52, 8.5, 0],
  ["U2", 8.28, 18.94, 49.16, 70.1, 8.5, 0],
  ["U3", 145.31, 181.51, 8.86, 19.52, 8.5, 0],
  ["U5", 25.6, 31.3, 46.18, 56.84, 8.5, 0],
  ["U6", 31.34, 37.04, 46.18, 56.84, 8.5, 0],
  ["U7", 51.74, 57.44, 46.18, 56.84, 8.5, 0],
  ["U8", 57.54, 63.24, 46.18, 56.84, 8.5, 0],
  ["U9", 126.235, 131.935, 46.18, 56.84, 8.5, 0],
  ["VD1", 122.25, 135.11, 92.4, 95.6, 3.5, 0],
  ["VD2", 153.31, 172.25, 92.15, 97.85, 6, 0],
  ["VT1", 52.27, 57.01, 38.91, 46.01, 8, 0],
  ["VT20", 9.625, 14.365, 38.29, 45.39, 8, 0],
  ["VT21", 124.61, 135.11, 83.5, 88.4, 19, 0],
  ["XS1", 175.4, 191.4, 84.75, 96.25, 11, 0],
  ["XS11", -0.17, 3.37, 48.97, 75.37, 8.5, 1],
  ["XS12", 105.58, 185.32, 74.03, 77.57, 8.5, 1],
  ["XS21", 10.17, 23.87, 34.93, 38.47, 8.5, 1],
  ["XS22", 46.22, 54.84, 34.93, 38.47, 8.5, 1],
  ["XS23", 67.51, 78.67, 34.93, 38.47, 8.5, 1],
  ["XS24", 113.345, 124.505, 34.93, 38.47, 8.5, 1],
  ["XS25", 152.78, 169.02, 34.93, 38.47, 8.5, 1],
];
NANO_BOX  = [-2.4, 43.82, 85.2, 103.48];  // board: U1 courtyard [X0, X1, Y0, Y1] (USB end at X0)
NANO_ROWS_Y = [86.73, 101.97];  // board: U1 pad rows (world Y); the mini-B sits midway
JACK_PIN1 = [177.4, 91.5];  // board: XS1 pin 1 [X, Y]
J1_BOX    = [41.55, 56.45, 6.8, 12.3];  // board: DRV J1 courtyard (display face)
FASCIA_HOLES = [[4.5, 4.5, 2.7], [4.5, 35.5, 2.7], [171.5, 4.5, 2.7], [171.5, 35.5, 2.7]];  // board: TS06-FASCIA [x, y, drill], fascia frame (y down from top)
FASCIA_CTRL  = [["SW1", 30, 14, 8.8], ["SW2", 95, 14, 8], ["SW3", 118, 14, 8], ["SW4", 146, 14, 8], ["SW5", 164, 14, 8]];  // board: SW1-SW5 [ref, x, y, panel hole]
FJ_BOX       = [143.4, 160.6, 28.3, 38.5];  // board: fascia J1 courtyard [x0, x1, y0, y1], back face
LEAD = [[49, 9, 33.1], [49, 9, 30.1], [49, -3.65, 30.1], [49, -6.65, 27.1], [156.31, -6.65, -2.39], [156.31, -2.51, -5.32]];  // derived: fascia lead centre line [X, Y, Z]

// ---- derived in case_pair.py; case.scad derives the same and echoes it for comparison
PY_Z_DISP_F     = 30;
PY_Z_DRV_B      = 44.2;
PY_PART_MAX     = 22;
PY_Z_REAR_IN    = 71.2;
PY_SOFFIT_Y     = 75.4;
PY_Y_FLOOR      = -7.3;
PY_Z_TOE        = -10.841;
PY_OUT_W        = 204.4;
PY_OUT_H        = 120.3;
PY_OUT_D        = 83.641;
