// params.scad - GENERATED by case_pair.py from boards.json and the DIMS table. Do not edit:
// change case_pair.py (or pass -D NAME=value to openscad for a quick what-if) and regenerate.
// World frame: X across the front from the clock's left, Y up (FreeCAD assembly), Z depth
// from the ИН-12 glass front, + toward the back. case.scad maps x = X, y = Z, z = Y.
// Kinds: board = read from the board files; doc = stated in a repo document; design = chosen
// here; assumed = typical value, not yet measured.


// ---- boards
BOARD_W            = 191.4;  // [board] tools/mkpcb_disp.py W = tools/mkpcb_drv.py W
DISP_H             = 44;  // [board] tools/mkpcb_disp.py H
DISP_TOP_Y         = 78;  // [board] tools/mkpcb_disp.py TOP: world Y of TS06-DISP's top edge
DRV_H              = 100;  // [board] tools/mkpcb_drv.py H
DRV_Y0             = 26;  // [board] tools/mkpcb_drv.py Y0: TS06-DRV's top edge is 26 above TS06-DISP's
PCB_T              = 1.6;  // [board] tools/pcbkit.py Board.thickness (both boards)
FASCIA_W           = 176;  // [board] PCB/TS06-FASCIA/TS06-FASCIA.kicad_pcb Edge.Cuts
FASCIA_H           = 40;  // [board] PCB/TS06-FASCIA/TS06-FASCIA.kicad_pcb Edge.Cuts (was 52, PCB/README.md)
FASCIA_X0          = 4.305;  // [design] the owner, 29.09.26: the fascia centred under the tube row, on the middle of H10 and ИН-15А (X 92.305), kept within the board width
FASCIA_T           = 2;  // [doc] PCB/README.md: TS06-FASCIA 2.0 mm FR4
FASCIA_HOLE_D      = 2.7;  // [board] TS06-FASCIA.kicad_pcb mounting holes (M2.5)

// ---- stack
PBS_H              = 8.5;  // [doc] PCB/TS06-DRV/bom.md: socket strip PBS, 8.5 mm (review finding 1: PBS runs 7.0-8.5)
PLS_BODY           = 2.5;  // [doc] PCB/TS06-DISP/bom.md: 11 mm = 8.5 PBS + 2.5 PLS body
IN12_W             = 19.47;  // [doc] 3d/IN12.FCStd envW (render/rev_f.py DIMS)
IN12_H             = 28.86;  // [doc] 3d/IN12.FCStd envH (render/rev_f.py DIMS)
IN12_D             = 25.5;  // [doc] 3d/IN12.FCStd envD: glass front to rear seating plane (measurements-IN12)
IN12_DIGIT         = 18.63;  // [doc] render/rev_f.py DIGIT_12, caliper 27.08
IN12_SEAT          = 4.5;  // [assumed] socket seat: review puts the socketed glass front ~30 in front of TS06-DISP; TS06-LIB-SOCKET is not captured
IN17_FACE          = 14;  // [doc] ИН-17 outline drawing: face 14 (measurements-IN17 Rev 5)
IN17_H             = 20;  // [doc] ИН-17 outline drawing: 20 across the long face axis
IN17_D             = 22;  // [doc] ИН-17 outline drawing: glass 22 long
IN17_STEM          = 20;  // [doc] ИН-17 outline drawing: round stem Ø20 at the base
IN17_DIGIT         = 9;  // [doc] render/rev_f.py DIGIT_17
IN17_STANDOFF_MIN  = 6.4;  // [doc] TS06_IN17_Socket descr: >= 6.4 mm glass to board (TU: no solder within 8 mm)
GLASS_ALLOW        = 0.4;  // [doc] TERMINAL-06-cad-component-library.md §7: glass gets max-of-sample + 0.4
LED_D              = 3;  // [board] TS06_LED_D3.0mm
LED_H              = 5.3;  // [assumed] 3 mm LED body height above the board
LED_FLANGE_D       = 3.8;  // [assumed] 3 mm LED flange diameter
INS1_D             = 6.97;  // [doc] TS06_INS1_Lamp descr: measured 6.97 mm envelope
PIN_TAIL           = 1.5;  // [assumed] trimmed through-hole lead + fillet proud of a board face
SCREW_HEAD         = 2;  // [assumed] M3 low head (DIN 7984 2.0; ISO 7380 1.65) - review finding 3
SCREW_HEAD_D       = 5.5;  // [assumed] M3 low-head diameter

// ---- design
CHEEK_T            = 6;  // [doc] pair review, envelope: 6 mm cheeks
CHEEK_CLR          = 0.5;  // [doc] pair review, envelope: 0.5 mm each side
GLASS_RECESS       = 1;  // [design] tube glass sits 1 mm behind the face plane, so a knock lands on the case
SILL_TOP_Y         = 39;  // [design] trench floor: above the XP21-25 pads (37.55; review: >= 38), below the ИН-17 LEDs' flange (41.49 - 1.9 = 39.59)
SILL_T             = 2;  // [design] printed
BACK_GAP           = 2.5;  // [design] no case part closer than this to TS06-DISP's front face (pin tails, screw heads)
TRENCH_L_X         = 3;  // [doc] pair review 4: the trench's left wall hides XP11, the left 3 mm
TRENCH_R_X         = 182.035;  // [design] right wall: ИН-15А (V10) glass + GLASS_ALLOW + 0.5, still hiding the H4 standoff screw and XP12's end
BROW_CLR           = 0.8;  // [design] soffit above the tall glass: 2 x GLASS_ALLOW
VALANCE_Y0         = 74;  // [doc] pair review 3: the brow covers the display board's top 4 mm (78 - 4)
VALANCE_T          = 1.5;  // [design] printed rib behind the ИН-17 pair
BROW_T             = 3;  // [design] printed brow face
SOFFIT_T           = 2;  // [design] printed
BROW_RAKE          = 12;  // [doc] spec §6: front raked 12° - the brow leans back like the fascia
TOP_T              = 3;  // [design] printed top plate, black like the chassis (case review m5; spec §6: chassis matte black)
MOD_CLR            = 0.5;  // [doc] the module's clearance to a case part it slides past: the pair review's 0.5 to each cheek
END_BLOCK          = 8;  // [doc] case review F7: every insert a cheek screw goes into sits in a block of at least 8 mm
TOP_CLR            = 5.5;  // [design] TS06-DRV's top edge to the top plate's underside: MOD_CLR + END_BLOCK - TOP_T, so the plate's rear block (the rear panel's inserts, the cheek screws) clears the board; was the pair review's 3
REAR_AIR           = 5;  // [doc] pair review, envelope: 5 mm of air in front of the rear panel
REAR_T             = 1.6;  // [doc] pair review suggestion 2: the rear panel is a 1.6 mm FR4 blank
BASE_T             = 3;  // [design] printed or 3 mm aluminium
KICK_T             = 2;  // [design] the raked strip under the fascia; thin enough to clear the fascia plug
FASCIA_RAKE        = 12;  // [doc] spec §6 and cad-component-library: front raked 12°
FLOOR_CLR          = 0.5;  // [design] between the fascia lead's lowest point and the floor
VENT_W             = 2;  // [doc] pair review 4: slots no wider than 2.5 mm (2.0 used)
VENT_X0            = 6.9;  // [board] case review m4: over the logic side - a 30 mm span (the pair review's) centred on U1, the Nano (courtyard X -2.4-43.8 in mkpcb_drv)
VENT_X1            = 36.9;  // [board] VENT_X0 + 30
VENT_Y0            = 85;  // [doc] pair review suggestion 2: world Y 85-100 (inside the Nano's Y 85.2-103.5)
VENT_Y1            = 100;  // [doc] pair review suggestion 2
VENT_PITCH         = 4.5;  // [design] 
VENT_HV_CLR        = 5;  // [design] no 185 V part (a pad on an HV-class net) within this of the vent field, projected
BOSS_W             = 8;  // [design] square boss on a cheek's inner face, M3 heat-set insert
BOSS_D             = 10;  // [design] boss length in Z, in front of TS06-DRV
FBOSS_D            = 8;  // [design] fascia boss depth behind the fascia
JACK_HOLE_D        = 9;  // [doc] pair review suggestion 3: Ø9 through
JACK_CB_D          = 14;  // [doc] pair review suggestion 3: Ø14 pocket (put on the OUTSIDE here - see checks)
JACK_WEB           = 1.5;  // [doc] pair review suggestion 3: thin the cheek to 1.5-2 mm
USB_SLOT_W         = 12;  // [doc] pair review suggestion 3: slot about 12 x 9 (12 along Y)
USB_SLOT_H         = 9;  // [doc] pair review suggestion 3 (9 along Z)
VIEW_DEG           = 10;  // [doc] cad-component-library §5 / spec §6: brow clearance at a 10° viewing angle

// ---- parts
JACK_BODY_L        = 14.5;  // [board] TS06_BarrelJack_Horizontal F.Fab: x -13.70..0.80
JACK_BODY_W        = 9;  // [board] TS06_BarrelJack_Horizontal F.Fab: y -4.51..4.50
JACK_BODY_H        = 11;  // [assumed] 5.5 x 2.1 PCB jack body height (PJ-002A class)
JACK_AXIS_H        = 6.5;  // [assumed] barrel axis above the board (PJ-002A class)
PLUG_BARREL_L      = 9.5;  // [assumed] 5.5 x 2.1 plug sleeve length (common 9.5; long-barrel 12/14 exist)
PLUG_NOSE_D        = 10;  // [assumed] plug overmould nose - larger than the Ø9 hole, so it stops on the web
JACK_ENGAGE_MIN    = 7;  // [assumed] sleeve engagement for both contacts to make
NANO_PCB_T         = 1.6;  // [assumed] Arduino Nano board
USB_H              = 4;  // [assumed] mini-B receptacle height above the Nano board
USB_W              = 7.7;  // [assumed] mini-B receptacle width
USB_L              = 9.2;  // [assumed] mini-B receptacle length
USB_PLUG_W         = 11;  // [assumed] mini-B plug overmould across Y
USB_PLUG_H         = 8;  // [assumed] mini-B plug overmould across Z
FJ_HDR_H           = 4.8;  // [assumed] JST S6B-PH-SM4-TB housing height off the fascia's back
FJ_PLUG_OUT        = 3;  // [assumed] mated PHR-6 beyond the header mouth, to where the wires leave it
CABLE_R            = 3;  // [assumed] bend radius of the 6-wire PH lead (to the ribbon's centre line)
CABLE_HALF         = 0.65;  // [assumed] half the lead's thickness (6 x AWG28 side by side)
J1_MATED_H         = 9.5;  // [assumed] B6B-PH-K 6.0 header + PHR-6 housing, off TS06-DRV's display-facing face
LEAD_LEN           = 190;  // [doc] PCB/TS06-DRV/bom.md: fascia lead, 6-way JST PH, 180-200 mm (the middle; was the pair review's 150)
ROTARY_D           = 25;  // [doc] knowledge/TERMINAL-06-spec.txt §6, MEASURE BEFORE ORDERING PANELS: body / wafer 25.00, which supersedes the withdrawn 26.94 (Rev D.3)
ROTARY_DEPTH       = 22;  // [doc] knowledge/TERMINAL-06-spec.txt §6: the lugs sit >= 11.3 behind the fascia's rear face, and the §1 table gives them 10 mm of free length: 21.3, rounded up
MT1_W              = 11.92;  // [doc] measurements-MT1 #2 (candidate W)
MT1_L              = 10.43;  // [doc] measurements-MT1 #1 (candidate L)
MT1_DEPTH          = 30;  // [assumed] cad-component-library: 'your spec says 30 mm depth; verify per sample'
KMD1_A             = 13.75;  // [doc] measurements-KMD1 #1 (orientation not known)
KMD1_B             = 16.91;  // [doc] measurements-KMD1 #2 (orientation not known)
KMD1_DEPTH         = 20;  // [assumed] КМД1-1 body depth: not captured (measurements-KMD1 #8)

// ---- fixings
INS_M3_D           = 4;  // [assumed] M3 heat-set insert: hole diameter (M3 x 5.7 class)
INS_M3_L           = 5.7;  // [assumed] M3 heat-set insert: length
INS_M25_D          = 3.5;  // [assumed] M2.5 heat-set insert: hole diameter
INS_M25_L          = 4;  // [assumed] M2.5 heat-set insert: length
INS_WALL_MIN       = 1.5;  // [doc] case review m4: at least 1.5 mm of wall round an insert
CLR_M3             = 3.4;  // [design] M3 clearance hole through a cheek
CB_D               = 6.2;  // [design] counterbore for an M3 socket head, from the cheek's outside
CB_DEPTH           = 2;  // [design] counterbore depth
SCREW_M3_L         = 8;  // [design] M3 x 8 through a cheek: 4 mm of cheek under the counterbore, 4 mm into the insert
SCREW_M25_L        = 6;  // [design] M2.5 x 6: fascia, rear panel, sill ties
MOD_WASHER_T       = 0.8;  // [assumed] nylon washer under the module screws' heads (PCB/TS06-DRV/bom.md: M3 + nylon washer)
TIP_CLR_MIN        = 1;  // [doc] case review F7: no screw within 1 mm of glass or a board
GLASS_BLK_CLR      = 1;  // [design] a new block under the tall glass stays this far below it (so it needs no lead-in)
BASE_FIX_Z         = 10;  // [design] front base screw: behind the fascia's lower bosses (Z <= 2.1)
WALL_FIX_Z         = 16;  // [design] trench screw: in the blocks under H10 / ИН-15А, behind the fascia's upper bosses (Z <= 8.6)
TOP_FIX_Z          = 20;  // [design] front top-plate screw: in front of TS06-DRV's strips (Z >= 34.1)
REAR_FIX_DZ        = 12;  // [design] rear base / top-plate screws this far in front of the rear panel
LEADIN             = 3;  // [doc] case review F8: 45° x 3 mm lead-ins on the rear edges the module passes within 1 mm
LEADIN_BELOW       = 1;  // [doc] case review F8: the square-edged clearances under 1 mm get one
LEAD_MARGIN        = 1;  // [design] a sill lead-in runs this far past the LED flange on each side
SLOT_X             = 0.6;  // [doc] case review F9: the crossmember holes slotted along X by ±0.6
PRINT_SHRINK       = 0.4;  // [assumed] PETG shrinkage along a long print, % (compensate the slicer's X scale)
REAR_HOLE_D        = 2.7;  // [design] M2.5 clearance in the FR4 rear panel (slotted ±SLOT_X along X)
REAR_FIX_X         = 4;  // [design] rear-panel corner screws this far in from the cheeks' inner faces

// ---- variant D
FASCIA_FRAME       = 0;  // [design] variant D, the printed fascia frame: 1 = on. Off by default: the owner has not chosen a fascia variant
FF_PANEL_W         = 179;  // [doc] case review, variant D: a 179 x 40 fascia, X 3.0-182.0 (no such board yet; the 176 board stands in)
FF_PANEL_H         = 40;  // [doc] case review, variant D
FF_WEB             = 4;  // [design] the frame's depth behind the panel
FF_LEDGE           = 2;  // [design] the rabbet's ledge behind the panel's left, right and bottom edges
FF_TOP             = 4.5;  // [design] the top rail behind the panel (under the sill): above the КМД1 bodies (t >= 5.5)
FF_RIB_W           = 2;  // [design] ribs under the panel's middle, between the controls
FF_HOLE_E          = 3;  // [design] the 179 panel's lower holes, in from its side edges (FR4 web 1.65)
FF_HOLE_T          = 5;  // [design] the 179 panel's holes, down from its top edge / up from its bottom edge
FF_FIX_T           = 20;  // [design] the cheek screw into the frame's end blocks, down the face
FF_TIE_Z           = 8;  // [design] the sill ties (M2.5, down through the sill into the frame's rib heads)

// ---- read from the boards (world coordinates)
IN12_X   = [13.21, 36.57, 63.99, 87.37];  // board: mkpcb_disp IN12_X (H10 H1 M10 M1)
IN15_X   = [150.4, 171.4];  // board: mkpcb_disp IN15_X (ИН-15Б, ИН-15А)
IN17_X   = [108.635, 129.135];  // board: mkpcb_disp IN17_X (S10, S1)
IN12_Y   = 60.166;  // board: TOP - Y12
IN17_Y   = 54.791;  // board: TOP - Y17
COLON    = [[50.535, 66.5], [50.535, 52.5]];  // board: V7, V8 (ИНС-1)
LEDS     = [[13.21, 42.496], [36.57, 42.496], [63.99, 42.496], [87.37, 42.496], [108.635, 41.491], [129.135, 41.491], [150.4, 42.496], [160.9, 42.496], [171.4, 42.496]];  // board: HL1-HL9
DISP_HOLES = [[3.5, 37.5], [187.9, 37.5], [50.535, 74.7], [187.9, 70.5]];  // board: mkpcb_disp H1-H4 (M3, the standoffs)
DRV_CASE_HOLES = [[187.9, 7.5], [3.5, 7.5], [187.9, 100.5], [3.5, 81.5]];  // board: mkpcb_drv HOLES H5-H8 -> cheeks
DISP_STRIPS = [["XP11", -0.17, 3.37, 48.97, 75.37], ["XP12", 105.58, 185.32, 74.03, 77.57], ["XP21", 10.17, 23.87, 34.93, 38.47], ["XP22", 46.22, 54.84, 34.93, 38.47], ["XP23", 67.51, 78.67, 34.93, 38.47], ["XP24", 113.345, 124.505, 34.93, 38.47], ["XP25", 152.78, 169.02, 34.93, 38.47]];  // board: XP courtyards [ref, X0, X1, Y0, Y1]
// TS06-DRV parts [ref, X0, X1, Y0, Y1, height, side]: side 0 = component face (to the rear),
// 1 = display face. Boxes are courtyards; heights per case_pair.py FP_H (kind in checks.md).
DRV_PARTS = [
  ["C1", 166.68, 173.78, 20.975, 23.975, 10, 0],
  ["C10", 140.11, 143.11, 83.7, 90.8, 10, 0],
  ["C11", 157.89, 160.89, 79.255, 86.355, 10, 0],
  ["C12", 154.59, 157.59, 84.1, 91.2, 10, 0],
  ["C13", 93.895, 100.995, 80.325, 83.325, 10, 0],
  ["C14", 85.64, 92.74, 91.12, 94.12, 10, 0],
  ["C15", 145.82, 152.92, 52.965, 55.965, 10, 0],
  ["C16", 153.44, 160.54, 52.965, 55.965, 10, 0],
  ["C17", 104.71, 111.81, 52.665, 55.665, 10, 0],
  ["C18", 33.51, 35.61, 17.45, 22.05, 8, 0],
  ["C19", 31.01, 33.11, 14.45, 19.05, 8, 0],
  ["C3", 86.275, 93.375, 94.785, 97.785, 10, 0],
  ["C4", 19, 22, 49.45, 56.55, 10, 0],
  ["C5", 38.55, 43.15, 52.45, 54.55, 8, 0],
  ["C6", 38.55, 43.15, 54.95, 57.05, 8, 0],
  ["C7", 101.15, 111.65, 85.25, 95.75, 20, 0],
  ["C8", 146.25, 153.05, 96.8, 103.6, 12.5, 0],
  ["C9", 136.3, 139.3, 83.7, 90.8, 10, 0],
  ["F1", 155.85, 173.85, 98.95, 102.45, 13, 0],
  ["J1", 41.55, 56.45, 6.8, 12.3, 9.5, 1],
  ["L1", 115.71, 146.15, 91.6, 103.6, 12, 0],
  ["R1", 52, 55, 58.51, 63.6, 11, 0],
  ["R20", 6.285, 9.285, 43.475, 48.565, 11, 0],
  ["R21", 25.7, 28.7, 58.79, 71.05, 3.5, 0],
  ["R22", 31.4, 34.4, 58.79, 71.05, 3.5, 0],
  ["R23", 33.9, 36.9, 76.41, 81.5, 11, 0],
  ["R24", 36.9, 39.9, 76.41, 81.5, 11, 0],
  ["R25", 39.9, 42.9, 76.41, 81.5, 11, 0],
  ["R26", 59, 62, 58.51, 63.6, 11, 0],
  ["R27", 15.92, 33.36, 42.75, 47.45, 4.7, 0],
  ["R28", 18.46, 35.9, 37.75, 42.45, 4.7, 0],
  ["R29", 70.72, 88.16, 42.75, 47.45, 4.7, 0],
  ["R30", 73.26, 90.7, 37.75, 42.45, 4.7, 0],
  ["R31", 101.315, 118.755, 38.05, 42.75, 4.7, 0],
  ["R32", 119.095, 136.535, 38.05, 42.75, 4.7, 0],
  ["R33", 15.735, 20.825, 28.46, 31.46, 11, 0],
  ["R34", 15.735, 20.825, 24.65, 27.65, 11, 0],
  ["R35", 10.02, 15.11, 28.46, 31.46, 11, 0],
  ["R36", 10.02, 15.11, 24.65, 27.65, 11, 0],
  ["R37", 65.11, 70.2, 43.63, 46.63, 11, 0],
  ["R38", 59.395, 64.485, 43.63, 46.63, 11, 0],
  ["R39", 67.65, 72.74, 38.55, 41.55, 11, 0],
  ["R40", 61.935, 67.025, 39.185, 42.185, 11, 0],
  ["R41", 116.095, 119.095, 43.445, 48.535, 11, 0],
  ["R42", 113.37, 118.46, 49.345, 52.345, 11, 0],
  ["R43", 119.905, 122.905, 43.445, 48.535, 11, 0],
  ["R44", 119.27, 122.27, 49.16, 54.25, 11, 0],
  ["R53", 55.5, 58.5, 58.51, 63.6, 11, 0],
  ["R54", 38.55, 43.64, 46.4, 49.4, 11, 0],
  ["R55", 38.55, 43.64, 49.4, 52.4, 11, 0],
  ["R56", 140.75, 158.19, 37.75, 42.45, 4.7, 0],
  ["R57", 148.37, 165.81, 42.75, 47.45, 4.7, 0],
  ["R58", 44.18, 48.88, 39.66, 57.1, 4.7, 0],
  ["R59", 49.18, 53.88, 39.66, 57.1, 4.7, 0],
  ["R60", 54.16, 71.6, 52.55, 57.25, 4.7, 0],
  ["R61", 54.16, 71.6, 47.55, 52.25, 4.7, 0],
  ["R62", 83.06, 100.5, 99.05, 103.75, 4.7, 0],
  ["R63", 78.05, 82.75, 85.06, 102.5, 4.7, 0],
  ["R64", 69.19, 81.45, 80.5, 83.5, 3.5, 0],
  ["R65", 72.41, 77.5, 93.66, 96.66, 11, 0],
  ["R66", 48.5, 51.5, 58.51, 63.6, 11, 0],
  ["R67", 119.48, 124.57, 82.485, 85.485, 11, 0],
  ["R68", 143.795, 146.795, 83.57, 88.66, 11, 0],
  ["R69", 94.185, 97.185, 83.95, 89.04, 11, 0],
  ["R70", 94.185, 97.185, 89.665, 94.755, 11, 0],
  ["R71", 72.41, 77.5, 89.85, 92.85, 11, 0],
  ["R72", 42.35, 54.61, 28.5, 31.5, 3.5, 0],
  ["R73", 23.35, 35.61, 22.5, 25.5, 3.5, 0],
  ["R74", 20.85, 33.11, 19.5, 22.5, 3.5, 0],
  ["R75", 51.99, 64.25, 87.7, 90.7, 3.5, 0],
  ["R76", 51.455, 63.715, 83.99, 86.99, 3.5, 0],
  ["RN1", 145.32, 166.26, 20.48, 31.14, 8.5, 0],
  ["RP1", 64.42, 74.46, 83.63, 88.96, 10.5, 0],
  ["U1", -2.4, 43.82, 85.2, 103.48, 16.6, 0],
  ["U10", 131.315, 137.015, 46.18, 56.84, 8.5, 0],
  ["U11", 125.26, 135.92, 80, 90.78, 8.5, 0],
  ["U12", 82.88, 93.54, 79.92, 90.7, 8.5, 0],
  ["U13", 58, 72.5, 12.68, 31.5, 15, 0],
  ["U14", 161.36, 173.47, 82.25, 91.25, 10.5, 0],
  ["U15", 136.79, 157.73, 60.86, 71.52, 8.5, 0],
  ["U16", 159.11, 180.05, 60.86, 71.52, 8.5, 0],
  ["U17", 105.77, 126.71, 60.86, 71.52, 8.5, 0],
  ["U2", 8.28, 18.94, 49.16, 70.1, 8.5, 0],
  ["U3", 145.31, 181.51, 8.86, 19.52, 8.5, 0],
  ["U5", 25.6, 31.3, 47.58, 58.24, 8.5, 0],
  ["U6", 31.34, 37.04, 47.58, 58.24, 8.5, 0],
  ["U7", 82.94, 88.64, 47.58, 58.24, 8.5, 0],
  ["U8", 88.74, 94.44, 47.58, 58.24, 8.5, 0],
  ["U9", 98.295, 103.995, 46.18, 56.84, 8.5, 0],
  ["VD1", 103.55, 116.41, 80.9, 84.1, 3.5, 0],
  ["VD2", 153.31, 172.25, 92.15, 97.85, 6, 0],
  ["VD3", 163.47, 176.33, 78.9, 82.1, 3.5, 0],
  ["VD4", 137.81, 156.75, 77.45, 83.15, 6, 0],
  ["VD5", 51.69, 64.55, 99.6, 102.8, 3.5, 0],
  ["VD6", 51.69, 64.55, 95.6, 98.8, 3.5, 0],
  ["VD7", 51.69, 64.55, 91.6, 94.8, 3.5, 0],
  ["VT1", 53.97, 58.71, 38.91, 46.01, 8, 0],
  ["VT2", 64.87, 71.97, 89.235, 93.975, 8, 0],
  ["VT20", 9.625, 14.365, 38.29, 45.39, 8, 0],
  ["VT21", 111.71, 122.21, 86, 90.9, 19, 0],
  ["XS1", 175.4, 191.4, 84.75, 96.25, 11, 0],
  ["XS11", -0.17, 3.37, 48.97, 75.37, 8.5, 1],
  ["XS12", 105.58, 185.32, 74.03, 77.57, 8.5, 1],
  ["XS21", 10.17, 23.87, 34.93, 38.47, 8.5, 1],
  ["XS22", 46.22, 54.84, 34.93, 38.47, 8.5, 1],
  ["XS23", 67.51, 78.67, 34.93, 38.47, 8.5, 1],
  ["XS24", 113.345, 124.505, 34.93, 38.47, 8.5, 1],
  ["XS25", 152.78, 169.02, 34.93, 38.47, 8.5, 1],
];
NANO_BOX  = [-2.4, 43.82, 85.2, 103.48];  // board: U1 courtyard [X0, X1, Y0, Y1] (USB end at X0)
NANO_ROWS_Y = [86.73, 101.97];  // board: U1 pad rows (world Y); the mini-B sits midway
JACK_PIN1 = [177.4, 91.5];  // board: XS1 pin 1 [X, Y]
J1_BOX    = [41.55, 56.45, 6.8, 12.3];  // board: DRV J1 courtyard (display face)
FASCIA_HOLES = [[4.5, 4.5, 2.7], [4.5, 35.5, 2.7], [171.5, 4.5, 2.7], [171.5, 35.5, 2.7]];  // board: TS06-FASCIA [x, y, drill], fascia frame (y down from top)
FASCIA_CTRL  = [["SW1", 30, 14, 8.8], ["SW2", 95, 14, 8], ["SW3", 118, 14, 8], ["SW4", 146, 14, 8], ["SW5", 164, 14, 8]];  // board: SW1-SW5 [ref, x, y, panel hole]
FJ_BOX       = [143.4, 160.6, 28.3, 38.5];  // board: fascia J1 courtyard [x0, x1, y0, y1], back face
LEAD = [[49, 9, 33.1], [49, 9, 30.1], [49, -3.65, 30.1], [49, -6.65, 27.1], [156.31, -6.65, -2.39], [156.31, -2.51, -5.32]];  // derived: fascia lead centre line [X, Y, Z]
FF_RIB_X = [71.8, 134.7];  // derived (variant D): the frame's ribs, in the two widest gaps between the stand-in's controls and back-side parts
FF_HOLES = [[71.8, 5], [134.7, 5], [6, 35], [179, 35]];  // derived (variant D): the 179 panel's M2.5 holes [X, down the face]: over the ribs, and its bottom corners

// ---- derived in case_pair.py; case.scad derives the same and echoes it for comparison
PY_Z_DISP_F     = 30;
PY_Z_DRV_B      = 44.2;
PY_PART_MAX     = 20;
PY_Z_REAR_IN    = 69.2;
PY_SOFFIT_Y     = 75.4;
PY_Y_FLOOR      = -7.3;
PY_Z_TOE        = -10.841;
PY_OUT_W        = 204.4;
PY_OUT_H        = 122.8;
PY_OUT_D        = 81.641;
PY_SILL_NOTCH_Z = 3.55;
PY_SILL_NOTCH_X0 = 20.805;
PY_FIX_BASE_Y   = -4.8;
PY_WALL_BLK_Y0  = 36.736;
PY_WALL_BLK_Y1  = 44.736;
PY_FIX_BROW_Y   = 93.45;
PY_FIX_BROW_Z   = 9.904;
PY_FIX_TOP_Y    = 108.5;
PY_TOP_LIP_Y0   = 104.5;
PY_FF_FIX_Y     = 18.19;
PY_FF_FIX_Z     = 0.711;
PY_SILL_LEAD_X0 = 105.735;
PY_REAR_SCREWS  = 6;
