#!/usr/bin/env python3
"""Bill of materials for either TS06-MAIN build, from the netlist module.

    python3 tools/bom_main.py            # PCB/TS06-MAIN/bom.md
    python3 tools/bom_main.py --tht      # PCB/TS06-MAIN-THT/bom.md

Grouped by value and footprint, references listed, DNP parts in their own table, with
the delta against the boards this one replaces (the inherited AlexGyver board, TS06-SEC,
TS06-COLON) spelled out at the end so the parts order can be checked against spec §7.
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ts06main as N

BUILD = "tht" if "--tht" in sys.argv else "smd"
BOARD = "TS06-MAIN-THT" if BUILD == "tht" else "TS06-MAIN"
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OUT = os.path.join(ROOT, "PCB", BOARD, "bom.md")


def value_for(p):
    v = p.value
    return v.split(" / ")[0 if BUILD == "smd" else 1] if " / " in v else v


def refsort(r):
    return (re.match(r"[A-Z]+", r).group(0), int(re.search(r"\d+", r).group(0)))


rows, dnp = {}, {}
for p in N.parts(BUILD):
    v = value_for(p)
    key = (p.sym, v.replace(" DNP", ""), p.fp(BUILD) or "-")
    (dnp if "DNP" in v else rows).setdefault(key, []).append(p.ref)

NAMES = {"R": "Resistor", "C": "Capacitor", "CP": "Electrolytic capacitor", "L": "Inductor", "Fuse": "PTC fuse",
         "D_Schottky": "Schottky diode", "D_Fast": "Fast rectifier", "LED": "LED, amber 3 mm", "Lamp_Neon": "Neon lamp ИНС-1",
         "Q_NPN_BEC": "NPN 300 V", "Q_NMOS_GDS": "N-MOSFET 500 V", "TLP627": "Optocoupler, Darlington", "K155ID1": "Nixie decoder К155ИД1",
         "MCP23017": "I2C port expander", "Arduino_Nano": "Arduino Nano", "LM393": "Dual comparator", "TC4420": "MOSFET driver",
         "DS3231": "RTC", "RTC_mini": "RTC module", "Reg_SIP3": "5 V switching regulator", "Jack_DC": "DC jack",
         "Trimmer": "Trimmer", "Tube_IN12": "Nixie tube", "Tube_IN17": "Nixie tube", "Battery": "Coin cell holder",
         "Conn_PH6": "JST PH connector, 6-way"}
lines = [f"# {BOARD} — bill of materials", "",
         f"Generated by `tools/bom_main.py{' --tht' if BUILD == 'tht' else ''}` from `tools/ts06main.py`; do not edit by hand.",
         f"{sum(len(v) for v in rows.values())} parts fitted, {sum(len(v) for v in dnp.values())} footprints left empty.", "",
         "| Qty | Part | Value | Footprint | References |", "|---|---|---|---|---|"]
for (sym, v, fp), refs in sorted(rows.items(), key=lambda kv: (kv[0][0], kv[0][1])):
    lines.append(f"| {len(refs)} | {NAMES.get(sym, sym)} | {v} | {fp} | {', '.join(sorted(refs, key=refsort))} |")
lines += ["", "## Not fitted (DNP) unless the bench asks for them", "", "| Qty | Part | Value | Footprint | References |", "|---|---|---|---|---|"]
for (sym, v, fp), refs in sorted(dnp.items()):
    lines.append(f"| {len(refs)} | {NAMES.get(sym, sym)} | {v} | {fp} | {', '.join(sorted(refs, key=refsort))} |")
lines += ["", "## What this board adds and removes against the three it replaces", "",
          "Compared with the inherited AlexGyver board + TS06-SEC + TS06-COLON, one TS06-MAIN unit needs:", "",
          "* **new:** the 12 V input stage (jack, PTC, Schottky, 100 µF), an R-78E5.0-1.0 regulator, a TC4420 driver, an LM393 comparator "
          "and the rail divider with its trimmer, one anode resistor per digit tube (six), four more TLP627 (six in all instead of the "
          "inherited four plus SEC's two), two more backlight LEDs (eight), and in the SMD build a bare DS3231SN with a CR2032 holder;",
          "* **unchanged in kind:** the Nano, the К155ИД1, the two MCP23017 and eighteen MPSA42/MMBTA42 with their base resistors, the two "
          "ИНС-1 with their own 220 kΩ ballasts, the eight tubes, the fascia connector;",
          "* **gone:** the inherited board itself, SEC's XS1/XS2/XS3/XS4 and the colon board's connector and harnesses, the 470 kΩ bleed "
          "trimmer and the shared 10 kΩ anode resistor of the old converter.", ""]
os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w", encoding="utf8", newline="\n").write("\n".join(lines))
print("wrote", os.path.relpath(OUT, ROOT), f"({sum(len(v) for v in rows.values())} fitted, {sum(len(v) for v in dnp.values())} DNP)")
