#!/usr/bin/env python3
"""Bills of materials for the through-hole pair, from the netlist module.

    python3 tools/bom_pair.py          # PCB/TS06-DISP/bom.md and PCB/TS06-DRV/bom.md

Grouped by kind, value and footprint, references listed, DNP parts in their own table, and
the hardware that is not on the netlist (IC sockets, the Nano's strips, standoffs) counted
from the footprints, so the order for one kit can be placed from these two files.
"""
import os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ts06pair as P

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")


def refsort(r):
    return (re.match(r"[A-Z]+", r).group(0), int(re.search(r"\d+", r).group(0)))


def kind(p):
    v, fp, ref = p.value, p.fp, p.ref
    if ref.startswith("RN"):
        return "Resistor network, isolated, DIP-16"
    if ref.startswith("RP"):
        return "Trimmer, multi-turn"
    if ref.startswith("R"):
        return "Resistor, 0.5 W 350 V" if "DIN0309" in fp else "Resistor, 0.25 W"
    if ref.startswith("C"):
        return "Electrolytic capacitor" if "CP_" in fp else "Ceramic capacitor"
    if ref.startswith("XP"):
        return "Pin header, straight (PLS)"
    if ref.startswith("XS") and "PinSocket" in fp:
        return "Socket strip, straight (PBS), 8.5 mm"
    table = {"XS1": "DC jack", "F1": "PTC fuse", "VD2": "Schottky diode", "VD1": "Fast rectifier",
             "U14": "5 V switching regulator", "U1": "Arduino Nano", "L1": "Inductor, radial",
             "VT21": "N-MOSFET 500 V", "U11": "MOSFET driver", "U12": "Dual comparator", "U3": "I2C port expander",
             "J1": "JST PH, vertical (top entry)", "U13": "DS3231 mini module (on a 5-way PBS)"}
    if ref in table:
        return table[ref]
    if ref.startswith("VT"):
        return "NPN 300 V"
    if v == "TLP627":
        return "Optocoupler, Darlington"
    if v == "K155ID1":
        return "Nixie decoder К155ИД1"
    if ref.startswith("HL"):
        return "LED, 3 mm"
    if v.startswith("IN-") or v.startswith("INS"):
        return "Nixie tube" if v != "INS-1" else "Neon lamp"
    return v


SOCKETS = {"TS06_DIP-16_W7.62mm_Socket": "DIP-16 socket, 300 mil", "TS06_DIP-8_W7.62mm_Socket": "DIP-8 socket, 300 mil",
           "TS06_DIP-4_W7.62mm_Socket": "DIP-4 socket, 300 mil", "TS06_DIP-28_W7.62mm_Socket": "DIP-28 socket, 300 mil (skinny)"}


def bom(board, name, extra):
    parts = sorted(P.parts(board).values(), key=lambda p: refsort(p.ref))
    rows, dnp = {}, {}
    for p in parts:
        key = (kind(p), p.value.replace(" DNP", ""), p.fp)
        (dnp if "DNP" in p.value else rows).setdefault(key, []).append(p.ref)
    hw = {}
    for p in parts:
        if p.fp in SOCKETS and not p.ref.startswith("RN"):        # the network is soldered in
            hw.setdefault(SOCKETS[p.fp], []).append(p.ref)
    lines = [f"# {name} — bill of materials", "",
             "Generated by `tools/bom_pair.py` from `tools/ts06pair.py`; do not edit by hand.",
             f"{sum(len(v) for v in rows.values())} parts fitted, {sum(len(v) for v in dnp.values())} footprints left empty. "
             "Every part is through-hole.", "",
             "| Qty | Part | Value | Footprint | References |", "|---|---|---|---|---|"]
    for (k, v, fp), refs in sorted(rows.items()):
        lines.append(f"| {len(refs)} | {k} | {v} | {fp} | {', '.join(refs)} |")
    if dnp:
        lines += ["", "## Not fitted (DNP) unless the bench asks for them", "",
                  "| Qty | Part | Value | Footprint | References |", "|---|---|---|---|---|"]
        for (k, v, fp), refs in sorted(dnp.items()):
            lines.append(f"| {len(refs)} | {k} | {v} | {fp} | {', '.join(refs)} |")
    lines += ["", "## Hardware", "", "| Qty | Item | For |", "|---|---|---|"]
    for k, refs in sorted(hw.items()):
        lines.append(f"| {len(refs)} | {k} | {', '.join(refs)} |")
    for q, item, what in extra:
        lines.append(f"| {q} | {item} | {what} |")
    out = os.path.join(ROOT, "PCB", name, "bom.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.relpath(out, ROOT)}: {sum(len(v) for v in rows.values())} fitted, "
          f"{sum(len(v) for v in dnp.values())} DNP")


if __name__ == "__main__":
    bom(P.DISP, "TS06-DISP", [(4, "Standoff M3, 11 mm, female-female, with 8 M3 × 6 screws",
                                "the four holes shared with TS06-DRV (11 mm = 8.5 mm PBS + 2.5 mm PLS body)"),
                               (4, "ИН-12 socket pins / panel sockets as the tube requires", "V1–V4")])
    bom(P.DRV, "TS06-DRV", [(2, "Socket strip PBS-15, 2.54 mm", "U1, the Nano stays removable"),
                             (2, "Mounting screw M3 + standoff to the case", "the two lower holes, H5 and H6"),
                             (1, "JST PH 6-way housing + crimps, cable to the fascia", "J1")])
